"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { AdminGate, adminHeaders } from "@/components/AdminGate";

type Alert = {
  id: string;
  agentSlug: string;
  alertType: string;
  severity: string;
  description: string;
  triggeringIds: string[];
  reviewedAt: string | null;
  createdAt: string;
};

function severityClass(severity: string) {
  if (severity === "CRITICAL") return "border-red-300 bg-red-50 text-red-800";
  if (severity === "WARNING") return "border-amber-300 bg-amber-50 text-amber-800";
  return "border-slate-200 bg-slate-50 text-slate-700";
}

export default function AdminMonitoringPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAll, setShowAll] = useState(false);

  async function load() {
    setLoading(true);
    const res = await fetch(`/api/admin/monitoring?unreviewed=${!showAll}`, {
      headers: adminHeaders()
    });
    const data = await res.json();
    setAlerts(data.alerts ?? []);
    setLoading(false);
  }

  useEffect(() => {
    void load();
  }, [showAll]); // eslint-disable-line react-hooks/exhaustive-deps

  async function markReviewed(id: string) {
    await fetch(`/api/admin/monitoring/${encodeURIComponent(id)}/review`, {
      method: "POST",
      headers: adminHeaders()
    });
    await load();
  }

  return (
    <AdminGate>
      <div className="space-y-6">
        <header className="space-y-2">
          <Link href="/admin" className="text-sm text-slate-500 hover:text-slate-800">
            Backstage
          </Link>
          <h1 className="text-3xl font-bold">Transaction monitoring</h1>
          <p className="text-slate-600">
            Alerts generated by velocity, amount-spike, and repeat-merchant checks. Alerts are
            created after each payment decision — non-blocking.
          </p>
        </header>

        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={() => setShowAll((v) => !v)}
            className="rounded-md border px-3 py-1.5 text-sm hover:bg-slate-50"
          >
            {showAll ? "Show unreviewed only" : "Show all alerts"}
          </button>
          <span className="text-sm text-slate-500">{alerts.length} alerts shown</span>
        </div>

        {loading ? (
          <p className="text-sm text-slate-500">Loading…</p>
        ) : alerts.length === 0 ? (
          <div className="rounded-xl border bg-white p-6 text-sm text-slate-500">
            No {showAll ? "" : "unreviewed "}monitoring alerts. Alerts appear after payment decisions
            trigger velocity, amount-spike, or repeat-merchant thresholds.
          </div>
        ) : (
          <div className="space-y-3">
            {alerts.map((alert) => (
              <div
                key={alert.id}
                className={`rounded-xl border p-4 ${severityClass(alert.severity)}`}
              >
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold uppercase tracking-wide">
                        {alert.alertType.replace(/_/g, " ")}
                      </span>
                      <span className="rounded-full border px-2 py-0.5 text-xs font-semibold">
                        {alert.severity}
                      </span>
                    </div>
                    <p className="font-medium">{alert.description}</p>
                    <p className="text-xs opacity-75">
                      Agent: {alert.agentSlug} ·{" "}
                      {new Date(alert.createdAt).toLocaleString()}
                    </p>
                    {Array.isArray(alert.triggeringIds) && alert.triggeringIds.length > 0 ? (
                      <p className="font-mono text-xs opacity-75">
                        Events: {alert.triggeringIds.slice(0, 3).join(", ")}
                        {alert.triggeringIds.length > 3
                          ? ` +${alert.triggeringIds.length - 3} more`
                          : ""}
                      </p>
                    ) : null}
                  </div>
                  <div className="flex items-center gap-2">
                    {alert.reviewedAt ? (
                      <span className="text-xs opacity-60">
                        Reviewed {new Date(alert.reviewedAt).toLocaleString()}
                      </span>
                    ) : (
                      <button
                        type="button"
                        onClick={() => markReviewed(alert.id)}
                        className="rounded-md border border-current bg-white/60 px-3 py-1 text-xs font-semibold hover:bg-white"
                      >
                        Mark reviewed
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </AdminGate>
  );
}
